In [1]:
import numpy as np 
from numpy import genfromtxt

In [2]:
#using Bank Authentication Data Set, which contain FEATURES of images not images

data = genfromtxt('bank_note_data.txt', delimiter = ',')

# separating each note by a string ','

In [3]:
data

# 0 is that the bank note is a forgery and 1 that it is real 
# 0 and 1 are two separate classes which will be obtained after feeding the model with the features...3.6216,8.6661 etc

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

#all the rows at the last column indexed at 4

In [5]:
labels #classes

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
# Spliting data for training and testing

X = features 
y = labels

#assigning to X and y because of convention

In [9]:
from sklearn.model_selection import train_test_split

#train_test_split will shuffle and split the data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#test size is splitting 1/3 for test, rest fro training and random state gives the same random values each time

In [11]:
X_test

#representing 33% of all features in X

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [12]:
X_train

#the rest 67% features for training

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
#Data preprocessing (Standardizing the Data)

#Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler_object = MinMaxScaler()

In [18]:
#fit only to the training data not test data, that would be cheating
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
#scaled_X_train.min()
#scaled_X_train.max()

#all values are now between 0 and 1
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [25]:
#building the model

from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()

#input layer, 8 neurons, expects input of 4 features 
model.add(Dense(4,input_dim=4,activation='relu'))

#hidden densely connected layer
model.add(Dense(8, activation='relu'))

#output layer, last layer to ouput 0 or 1 (labels)
model.add(Dense(1,activation='sigmoid'))

In [28]:
#compiling the model reequires a loss function,optimizer and metrics

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [43]:
#training the model on training data 

model.fit(scaled_X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
29/29 - 0s - loss: 0.1336 - accuracy: 0.9706 - 39ms/epoch - 1ms/step
Epoch 2/100
29/29 - 0s - loss: 0.1282 - accuracy: 0.9706 - 38ms/epoch - 1ms/step
Epoch 3/100
29/29 - 0s - loss: 0.1246 - accuracy: 0.9706 - 38ms/epoch - 1ms/step
Epoch 4/100
29/29 - 0s - loss: 0.1196 - accuracy: 0.9750 - 43ms/epoch - 1ms/step
Epoch 5/100
29/29 - 0s - loss: 0.1164 - accuracy: 0.9771 - 42ms/epoch - 1ms/step
Epoch 6/100
29/29 - 0s - loss: 0.1123 - accuracy: 0.9761 - 42ms/epoch - 1ms/step
Epoch 7/100
29/29 - 0s - loss: 0.1092 - accuracy: 0.9771 - 39ms/epoch - 1ms/step
Epoch 8/100
29/29 - 0s - loss: 0.1055 - accuracy: 0.9771 - 37ms/epoch - 1ms/step
Epoch 9/100
29/29 - 0s - loss: 0.1021 - accuracy: 0.9826 - 38ms/epoch - 1ms/step
Epoch 10/100
29/29 - 0s - loss: 0.0991 - accuracy: 0.9815 - 36ms/epoch - 1ms/step
Epoch 11/100
29/29 - 0s - loss: 0.0961 - accuracy: 0.9837 - 36ms/epoch - 1ms/step
Epoch 12/100
29/29 - 0s - loss: 0.0930 - accuracy: 0.9859 - 37ms/epoch - 1ms/step
Epoch 13/100
29/29 - 0s -

In [44]:
#testing model on test data 

# model.predict_classes(Scaled_X_test)

predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 1ms/step


In [45]:
#predictions

In [46]:
#evaluating the model 

model.metrics_names

['loss', 'accuracy']

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  0, 196]], dtype=int64)

In [49]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99       257
         1.0       0.98      1.00      0.99       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



In [50]:
#saving and loading a model

model.save('supermodel.h5')

In [42]:
from keras.models import load_model

new_model = load_model('supermodel.h5')